sudo: required
services:
  - docker

before_install:
  - docker build -t humeji/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true humeji/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "Docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-591330224397"
  backet_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
