version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # Outside the container mapped to inside the container.
    volumes:
      - /app/node_modules
      - .:/app  # : means tha twe are mapping to the local file system
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app  # : means tha twe are mapping to the local file system
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]
